name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Starts a new task using the specified task definition'
inputs:
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: false
    default: 'default'
  task-definition:
    description: 'The family and revision (family:revision) or full ARN of the task definition to run. If a revision is not specified, the latest ACTIVE revision is used.'
    required: true
  launch-type:
    description: "The type of task to launch ('EC2' or 'FARGATE')"
    required: true
  subnets:
    description: 'The subnet IDs (comma seperated) in which to run the task'
    required: false
  security-groups:
    description: 'The security group IDs (comma seperated) in which to run the task'
    required: false
  assign-public-ip:
    description: "Whether or not to assign a public IP to the task ('ENABLED' or 'DISABLED')"
    required: false
  tags:
    description: "The tags (key:value, comma seperated) to assign to the task"
    required: false
  wait-for-task-running:
    description: "Whether or not to wait for the Task to be running (defaults to 'true')"
    required: false
outputs:
  task-arn:
    description: 'The ARN of the task that was started'
runs:
  using: 'node12'
  main: 'dist/index.js'
